# Generated by Django 2.2.1 on 2019-05-10 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentaires',
            new_name='Commentaire',
        ),
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.CharField(max_length=50, null=True, verbose_name="auteur de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de parution'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='vitrine.Tag'),
        ),
    ]
