# Generated by Django 2.2.1 on 2019-05-15 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author_to_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliotheque.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=40)),
                ('firstname', models.CharField(max_length=40)),
                ('student_number', models.CharField(max_length=10, null=True)),
                ('mail', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('nb_items', models.IntegerField(default=0)),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['year', 'lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('serial_nb', models.IntegerField(null=True)),
                ('ean', models.CharField(max_length=13, null=True)),
                ('buy_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('reference', models.CharField(max_length=10, unique=True)),
                ('kind', models.CharField(max_length=1)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bibliotheque.Editor')),
                ('id', models.ManyToManyField(related_name='auteur', through='bibliotheque.Author_to_book', to='bibliotheque.Author')),
                ('serial_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bibliotheque.Serial')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bibliotheque.User')),
            ],
            options={
                'ordering': ['kind', 'title'],
            },
        ),
        migrations.AddField(
            model_name='author_to_book',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliotheque.Book'),
        ),
        migrations.AlterUniqueTogether(
            name='author_to_book',
            unique_together={('author_id', 'book_id')},
        ),
    ]
